/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proy1.DatosGlobales1;
import proy1.Profesor;

/**
 *
 * @author LightDemon12
 */
public class VentanaCrearCurso extends javax.swing.JFrame {
    private DatosGlobales1 datosGlobales1 = DatosGlobales1.getInstance();
    private ArrayList<Profesor> profesores = datosGlobales1.getPROFESORES1(); 
    private ModeloTablas.ModeloTablasCurso modeloTablasCurso; 
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(); 
    
    /**
     * Creates new form VentanaCrearCurso
     */
    public VentanaCrearCurso(ModeloTablas.ModeloTablasCurso modeloTablasCurso) {
        initComponents();
        this.modeloTablasCurso = modeloTablasCurso; 
        for (Profesor profesor: datosGlobales1.getPROFESORES1()){ 
            comboBoxModel.addElement(profesor.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigoc = new javax.swing.JTextField();
        txtnombrec = new javax.swing.JTextField();
        txtcreditoC = new javax.swing.JTextField();
        BoxPorfesores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonagregarcurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Créditos");

        jLabel4.setText("Profesor");

        txtcodigoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigocActionPerformed(evt);
            }
        });

        BoxPorfesores.setModel(comboBoxModel);
        BoxPorfesores.setToolTipText("");
        BoxPorfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPorfesoresActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Agregar Nuevo Curso");

        jButtonagregarcurso.setText("Agregar");
        jButtonagregarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagregarcursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonagregarcurso, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtcodigoc)
                            .addComponent(txtnombrec)
                            .addComponent(txtcreditoC)
                            .addComponent(BoxPorfesores, 0, 280, Short.MAX_VALUE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcreditoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BoxPorfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButtonagregarcurso)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxPorfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPorfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPorfesoresActionPerformed

    private void txtcodigocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocActionPerformed

    private void jButtonagregarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonagregarcursoActionPerformed
 modeloTablasCurso.agregarCursos(txtcodigoc.getText(),txtnombrec.getText(), Integer.parseInt(txtcreditoC.getText()), (String) (comboBoxModel.getSelectedItem()));
        
        

        
        
    }//GEN-LAST:event_jButtonagregarcursoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxPorfesores;
    private javax.swing.JButton jButtonagregarcurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcodigoc;
    private javax.swing.JTextField txtcreditoC;
    private javax.swing.JTextField txtnombrec;
    // End of variables declaration//GEN-END:variables
}
