/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ModeloListas.ModeloListasCurso;
import ModeloListas.ModeloListasCursoEstudiante;
import proy1.Cursos;

/**
 *
 * @author LightDemon12
 */
public class VentanaAlumno extends javax.swing.JFrame {
    ModeloListasCursoEstudiante modeloListasCursoEstudiante = new ModeloListasCursoEstudiante();

    /**
     * Creates new form VentanaAlumno
     */
    public VentanaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlumno = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cursos Asignados");

        jListAlumno.setModel(modeloListasCursoEstudiante);
        jListAlumno.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAlumnoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListAlumno);

        jButton1.setText("Actualizar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar Seccion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  VentanaActualziarDatos ventanaActualziarDatos = new VentanaActualziarDatos(); 
       ventanaActualziarDatos.setVisible(true);
       ventanaActualziarDatos.setLocationRelativeTo(null);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListAlumnoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAlumnoValueChanged
       if (!evt.getValueIsAdjusting()){
    int selectedIndex = jListAlumno.getSelectedIndex(); 
    if (selectedIndex!=-1){
        String filaSeleccionada = (String) jListAlumno.getSelectedValue();
        String[] filaConSplit = filaSeleccionada.split("-");
        String nombreCurso; 
        Cursos cursos = null; 
         if (filaConSplit.length==2){
            nombreCurso = filaConSplit[0]; 
            cursos = modeloListasCursoEstudiante.buscarCursosPorNombreEstudiante(nombreCurso);
            
             
         }
        if (cursos !=null){
            VentanaCursoEstudiante ventanaCursoEstudiante = new VentanaCursoEstudiante(cursos);
            ventanaCursoEstudiante.setVisible(true);
            ventanaCursoEstudiante.setLocationRelativeTo(this);
                    this.setVisible(false);
        }
    }
}
    }//GEN-LAST:event_jListAlumnoValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Ventanaprincipal ventanaPrincipal = new Ventanaprincipal(); 
         this.dispose();  
    ventanaPrincipal.setVisible(true);  
        ventanaPrincipal.setLocationRelativeTo(null);  
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
