/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import proy1.Administrador1;
import proy1.Alumnos;
import proy1.DatosGlobales1;
import proy1.Profesor;

/**
 *
 * @author LightDemon12
 */
public class Ventanaprincipal extends javax.swing.JFrame {
private  DatosGlobales1 datosGlobales; 
private Administrador1 administrador; 
    /**
     * Creates new form Ventanaprincipal
     */
    public Ventanaprincipal() {
        datosGlobales = DatosGlobales1.getInstance(); 
        administrador = datosGlobales.getADMINISTRADOR();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jbotonseccion1 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtcontra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("DTT");

        jLabel2.setText("Codigo");

        jLabel3.setText("Contraseña");

        Jbotonseccion1.setText("Iniciar seccion ");
        Jbotonseccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbotonseccion1ActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jbotonseccion1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtCodigo)
                    .addComponent(txtcontra))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Jbotonseccion1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraActionPerformed
           
       
      
    }//GEN-LAST:event_txtcontraActionPerformed

    private void Jbotonseccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbotonseccion1ActionPerformed
      VentanaAdmin ventanaAdmin = new VentanaAdmin(); 
             VentanaProfesor ventanaProfesor = new VentanaProfesor(); 
                VentanaAlumno ventanaAlumno = new VentanaAlumno();
   String codigoIngresado = txtCodigo.getText();
    String contrasenaIngresada = txtcontra.getText();
    
    if (administrador.getCodigo().equals(codigoIngresado) && administrador.getContrasena().equals(contrasenaIngresada)) {
        System.out.println("Autenticación de administrador exitosa.");
        this.setVisible(false);
        ventanaAdmin.setVisible(true);
        ventanaAdmin.setLocationRelativeTo(null);
    } else {
        for (Profesor profesor : datosGlobales.getPROFESORES1()) {
            if (profesor.getCodigo().equals(codigoIngresado) && profesor.getContrasena().equals(contrasenaIngresada)) {
                System.out.println("Autenticación de profesor exitosa.");
                this.setVisible(false);
                ventanaProfesor.setVisible(true);
                ventanaProfesor.setLocationRelativeTo(null);
                return; 
            }
        }
        for (Alumnos alumnos : datosGlobales.getALUMNOS()) {
            if (alumnos.getCodigo().equals(codigoIngresado) && alumnos.getContrasena().equals(contrasenaIngresada)) {
                System.out.println("Autenticación de alumno exitosa.");
                this.setVisible(false);
                ventanaAlumno.setVisible(true);
                ventanaAlumno.setLocationRelativeTo(null);
                return; 
            }
        }
        System.out.println("Error de autenticación.");
        Error ventanaError = new Error();
        ventanaError.setVisible(true);
        ventanaError.setLocationRelativeTo(null);
    }
    


    }//GEN-LAST:event_Jbotonseccion1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbotonseccion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtcontra;
    // End of variables declaration//GEN-END:variables
}
